#ifndef GL_STATE_CACHE_H_
#define GL_STATE_CACHE_H_
#include "Auto.h"
#include "OpenGLGather.h"
enum {
	VERTEX_ATTRIB_NONE = 0,
	VERTEX_ATTRIB_POSITION = 1 << 0,
	VERTEX_ATTRIB_COLOR = 1 << 1,
	VERTEX_ATTRIB_TEXCOORD = 1 << 2,
	VERTEX_ATTRIB_NORMAL = 1 << 3,
	VERTEX_ATTRIB_BLEND_WEIGHT = 1 << 4,
	VERTEX_ATTRIB_BLEND_INDEX = 1 << 5,
	VERTEX_ATTRIB_POS_COLOR_TEX = (VERTEX_ATTRIB_POSITION | VERTEX_ATTRIB_COLOR | VERTEX_ATTRIB_TEXCOORD),

	VERTEX_SIZE
};

void EnableVertexAttribs(UInt32 flags);
void BindTexture2D(GLuint textureID);

#endif //!GL_STATE_CACHE_H_
