#pragma once
#define uAntiAliasingSpace 0
#define uDebugSpace 0
#define uDeferredShadingSpace 0
#define uDepthTest 0
#define uFrameBuffers 0
#define uBloomSpace 0
#define uHDRSpace 0
#define uMassInstantiationSpace 0
#define uMoreCameraSpace 0
#define uMultLightsSpace 0
#define uPBRSpace 0
#define uPBRSkyBoxSpace 0
#define uShadowSpace 0
#define uSkyBoxSpace 0
#define uSSAOSpace 0
#define uStencilTestSpace 0
#define uTextureSpace 0
#define uNormalMappingSpace 0
#define uParallaxMappingSpace 0
#define uVertexExplodeSpace 0
