#include "Renderer//RendererDef.h"
#include <bgfx/bgfx.h>

namespace Auto3D
{

FRenderState FRenderState::_renderState[FRenderState::Count] =
{
	{ // Default
	0
	| BGFX_STATE_WRITE_RGB
	| BGFX_STATE_WRITE_A
	| BGFX_STATE_DEPTH_TEST_LEQUAL
	| BGFX_STATE_WRITE_Z
	| BGFX_STATE_CULL_CCW
	| BGFX_STATE_MSAA
	, UINT32_MAX
	, BGFX_STENCIL_NONE
	, BGFX_STENCIL_NONE
},
{ // ShadowMap_PackDepth
	0
	| BGFX_STATE_WRITE_RGB
	| BGFX_STATE_WRITE_A
	| BGFX_STATE_WRITE_Z
	| BGFX_STATE_DEPTH_TEST_LEQUAL
	| BGFX_STATE_CULL_CCW
	| BGFX_STATE_MSAA
	, UINT32_MAX
	, BGFX_STENCIL_NONE
	, BGFX_STENCIL_NONE
},
{ // ShadowMap_PackDepthHoriz
	0
	| BGFX_STATE_WRITE_RGB
	| BGFX_STATE_WRITE_A
	| BGFX_STATE_WRITE_Z
	| BGFX_STATE_DEPTH_TEST_LEQUAL
	| BGFX_STATE_CULL_CCW
	| BGFX_STATE_MSAA
	, UINT32_MAX
	, BGFX_STENCIL_TEST_EQUAL
	| BGFX_STENCIL_FUNC_REF(1)
	| BGFX_STENCIL_FUNC_RMASK(0xff)
	| BGFX_STENCIL_OP_FAIL_S_KEEP
	| BGFX_STENCIL_OP_FAIL_Z_KEEP
	| BGFX_STENCIL_OP_PASS_Z_KEEP
	, BGFX_STENCIL_NONE
},
{ // ShadowMap_PackDepthVert
	0
	| BGFX_STATE_WRITE_RGB
	| BGFX_STATE_WRITE_A
	| BGFX_STATE_WRITE_Z
	| BGFX_STATE_DEPTH_TEST_LEQUAL
	| BGFX_STATE_CULL_CCW
	| BGFX_STATE_MSAA
	, UINT32_MAX
	, BGFX_STENCIL_TEST_EQUAL
	| BGFX_STENCIL_FUNC_REF(0)
	| BGFX_STENCIL_FUNC_RMASK(0xff)
	| BGFX_STENCIL_OP_FAIL_S_KEEP
	| BGFX_STENCIL_OP_FAIL_Z_KEEP
	| BGFX_STENCIL_OP_PASS_Z_KEEP
	, BGFX_STENCIL_NONE
},
{ // Custom_BlendLightTexture
	BGFX_STATE_WRITE_RGB
	| BGFX_STATE_WRITE_A
	| BGFX_STATE_WRITE_Z
	| BGFX_STATE_DEPTH_TEST_LEQUAL
	| BGFX_STATE_BLEND_FUNC(BGFX_STATE_BLEND_SRC_COLOR, BGFX_STATE_BLEND_INV_SRC_COLOR)
	| BGFX_STATE_CULL_CCW
	| BGFX_STATE_MSAA
	, UINT32_MAX
	, BGFX_STENCIL_NONE
	, BGFX_STENCIL_NONE
},
{ // Custom_DrawPlaneBottom
	BGFX_STATE_WRITE_RGB
	| BGFX_STATE_CULL_CW
	| BGFX_STATE_MSAA
	, UINT32_MAX
	, BGFX_STENCIL_NONE
	, BGFX_STENCIL_NONE
},
};
}